cors:
  origins:
    patterns:
      #- http://localhost:8080
      #- http://localhost:3000
      #- https://www.example.com
security:
  jwt:
    token:
      secret-key: 53cr3t7
      expire-length: 3600000

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: projeto_rest_spring_boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto_rest_spring_boot?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: root
    password: S@Jr%ilh%754vV
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: false
    out-of-order: false
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: projeto.spring.boot@gmail.com
    password: fhjz lluv tqkr zaxp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    root: INFO

spring-doc:
  paths-to-match: /api/**/v1/**,/auth/**
  swagger-ui:
    use-root-path: true
