spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/projeto_rest_spring_boot?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin123
